<?php
/**
 * This is the template for generating the ActiveQuery class.
 */

/* @var $this yii\web\View */
/* @var $generator yii\gii\generators\model\Generator */
/* @var $tableName string full table name */
/* @var $className string class name */
/* @var $tableSchema yii\db\TableSchema */
/* @var $labels string[] list of attribute labels (name => label) */
/* @var $rules string[] list of validation rules */
/* @var $relations array list of relations (name => relation declaration) */
/* @var $className string class name */
/* @var $modelClassName string related model class name */

$modelFullClassName = $modelClassName;
if ($generator->ns !== $generator->queryNs) {
    $modelFullClassName = '\\' . $generator->ns . '\\' . $modelFullClassName;
}

echo "<?php\n";
?>

namespace <?= $generator->queryNs ?>;

/**
 * This is the ActiveQuery class for [[<?= $modelFullClassName ?>]].
 *
 * @see <?= $modelFullClassName . "\n" ?>
 */
class <?= $className ?> extends <?= '\\' . ltrim($generator->queryBaseClass, '\\') . "\n" ?>
{
    /*public function active()
    {
        return $this->andWhere('[[status]]=1');
    }*/

    /**
     * Auto-generated by Gii-<?=$giiVersion?> <?="\n"?>
     * {@inheritdoc}
     * @return <?= $modelFullClassName ?>[]|array
     */
    public function all($db = null)
    {
        return parent::all($db);
    }

    /**
     * Auto-generated by Gii-<?=$giiVersion?> <?="\n"?>
     * {@inheritdoc}
     * @return <?= $modelFullClassName ?>|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }

    /**
    * Auto-generated by Gii-<?=$giiVersion?> <?="\n"?>
    * @param <?= $modelFullClassName ?> $model
    * @return $this
    */
    public function search($model)
    {
<?php foreach ($properties as $property => $data):
    if(class_exists('\\' . $generator->ns . '\\' . $modelFullClassName)){
        if($property === ('\\' . $generator->ns . '\\' . $modelFullClassName)::getSoftDeleteAttribute()){
            continue;
        }
    }else{
        if($property === ($generator->baseClass)::getSoftDeleteAttribute()){
            continue;
        }
    }
    if($data['type'] === 'string'):?>
        $this->andFilterWhere(['like', '<?=$property?>', $model-><?=$property?>]);
<?php else:?>
        $this->andFilterWhere(['<?=$property?>' => $model-><?=$property?>]);
<?php endif;?>
<?php endforeach; ?>
        return $this;
    }
}