language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.4.2"
#  - travis_retry composer update --prefer-dist --no-interaction
  - travis_retry composer install --prefer-dist --no-interaction
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php
#    composer require "codeception/base: ^2.2.3"
#    composer require "codeception/verify: ~0.3.1"
#    composer require "codeception/specify: ~0.4.3"

before_script: echo "env.name=dev" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
#  - |
    - phpunit -v
    - php -S localhost:8080 -t web > /dev/null 2>&1 &
    - php -r 'echo get_cfg_var("env.name");';
#    vendor/bin/codecept run
