language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
#  - nightly

# faster builds on new travis setup not using sudo
sudo: false

#matrix:
#  allow_failures:
#    - php: nightly

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - wget -c -O ~/composer https://getcomposer.org/download/1.10.19/composer.phar && chmod +x ~/composer
  - php ~/composer --version
  - travis_retry ~/composer global require "fxp/composer-asset-plugin:^1.4.2"
#  - travis_retry composer update --prefer-dist --no-interaction
  - travis_retry ~/composer install --prefer-dist --no-interaction
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php

before_script: echo "env.name=dev" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
#  - |
#    - phpunit -v
    - php -r 'echo get_cfg_var("env.name");';
#    - php -S localhost:8080 -t web > /dev/null 2>&1 &
#    vendor/bin/codecept run
