version: "3.4"

services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - env_name=dev
#          - env_db_host=127.0.0.1
      ports:
        - target: 80
          published: 80
          protocol: tcp
          mode: host
    cron:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - env_name=dev
#          - env_db_host=127.0.0.1

