version: "3"

services:
    web:
#        image: taobig/nginx-php7-fpm:7.0
#        build: ./_docker
        build:
          context: .
          dockerfile: Dockerfile
          args:
            - env_name=dev
        ports:
            - "80:80"
        volumes:
            - .:/app
#        dns:
#            - 223.5.5.5
#            - 223.6.6.6

