version: "3"

services:
    web:
#        image: taobig/nginx_php70
#        build: ./_docker
        build:
          context: ./_docker
          args:
            - env_name=dev
        ports:
            - "80:80"
        volumes:
            - .:/app
#            - ./_docker:/etc/nginx/conf.d
        dns:
            - 223.5.5.5
            - 223.6.6.6

