version: "3.4"

# docker-compose -f docker-compose.yml -f docker-compose-dev.yml config
x-env:
  &env-setting
  env_name: prod
  env_memory_limit: 1024M
#  env_db_host: 127.0.0.1

services:
  web:
    #image: taobig/nginx-php7-fpm:7.0
    #build: ./_docker
    build:
      context: .
      dockerfile: Dockerfile
      args: *env-setting
    #https://docs.docker.com/compose/compose-file/#ports
#    ports:
#      - target: 80
#        published: 8001
#        protocol: tcp
#        mode: host
    volumes:
      - .:/app
  #        dns:
  #            - 223.5.5.5
  #            - 223.6.6.6


